### ISSUE TITLE
Unable to build application due to missing type declarations

### ISSUE THREAD

**Issue by fxnm** [mapbox/mapbox-gl-js#13680]
### mapbox-gl-js version

3.24.0

### Browser and version

any

### Expected behavior

Build successfully typescript application

### Actual behavior

Build fails because of missing type declarations in mapboxgl

### Link to the demonstration

https://github.com/fxnm/mapbox-gl-bug-report

### Steps to trigger the unexpected behavior

1. init vite app
2. add mapbox-gl
3. setup basic app
4. build applications

### Relevant log output

```shell
$ npm run build


node_modules/mapbox-gl/dist/mapbox-gl.d.ts:4:79 - error TS2307: Cannot find module '@tweakpane/core' or its corresponding type declarations.

4 import { BindingApi, BindingParams, ButtonApi, FolderApi, FolderParams } from '@tweakpane/core';
                                                                                ~~~~~~~~~~~~~~~~~

node_modules/mapbox-gl/dist/mapbox-gl.d.ts:10:22 - error TS2307: Cannot find module 'tweakpane' or its corresponding type declarations.

10 import { Pane } from 'tweakpane';
                        ~~~~~~~~~~~


Found 2 errors.


Process finished with exit code 2
```

**Comment by studds** [comment]
Introduced by 847bc850c1a9b9b7c9db254f9173ecb5f3fcc1cc

**Comment by stepankuzmin** [comment]
Hi @fxnm,

This is fixed in https://github.com/mapbox/mapbox-gl-js/commit/70486667c3dedf7936f35288edce2458d557734f and will be available in the upcoming `v3.26.0-rc.1` release. I'll close this now, but please feel free to tag me if that doesn't resolve the issue.
