### ISSUE TITLE
"Uncaught TypeError: e is not a function at vu.receive" in Chrome 65 or earlier

### ISSUE THREAD

**Issue by aleksejleonov** [mapbox/mapbox-gl-js#7904]
**mapbox-gl-js version**:

0.53.0

**browser**:

Chrome 65 or earlier version. Could be reproduced both on Win10 and Mac OS Mojave.
Starting Chrome 66 can't reproduce error.

### Steps to Trigger Behavior

 1. Open single-map example https://docs.mapbox.com/mapbox-gl-js/example/simple-map/ in Chrome 65 (or earlier version).
 2. Make several rapid zoom in/out (with touchpad) with large zoom level change (from city to planet level).

### Link to Demonstration

https://docs.mapbox.com/mapbox-gl-js/example/simple-map/

### Expected Behavior

No JS errors in console. 

### Actual Behavior

`Uncaught TypeError: e is not a function at vu.receive (actor.js94)` errors in browser console.

<img width="1498" alt="screen shot 2019-02-14 at 4 33 29 pm" src="https://user-images.githubusercontent.com/241582/52794605-cae93280-3078-11e9-8671-e5733f2cfddf.png">

**Comment by ryanhamley** [comment]
Also reported here with specific information on the cause of this bug: https://github.com/mapbox/mapbox-gl-js/issues/7905#issue-410354816

I believe the bug was introduced in https://github.com/mapbox/mapbox-gl-js/commit/913d3752444556d72460d1060048c9b428ef1715

**Comment by asheemmamoowala** [comment]
cc @mourner

**Comment by mourner** [comment]
> I believe the bug was introduced in 913d375

Nope — I ran `git bisect` while testing on older Chrome (using [these instructions](https://stackoverflow.com/a/19672729/244789)), and the culprit is #7818 (cc @kkaefer). Which is plausible given changes in the `actor.js` code, although I have no idea what changed in Chrome v65 that made the bug disappear.

**Comment by mourner** [comment]
Fixed in #7988. Looks like IE11 was affected too.
