### ISSUE TITLE
Browser/Platform specific rendering issues with 0.17.0

### ISSUE THREAD

**Issue by tobinbradley** [mapbox/mapbox-gl-js#2473]
I'm seeing some odd rendering issues with 0.17.0, but it's highly platform and browser specific. I can see the problem on the map on the API example page, but here's a [jsbin of it](http://jsbin.com/tihoyihudu/edit?html,output).

With Chrome 50 on Linux (Arch kernel 4.4) using Nvidia proprietary drivers, and with Chrome 49 on two different Chromebooks (Chrome OS, different ARM-based GPU's), the map doesn't render labels and the lines are strange:

![Chrome](http://i.imgur.com/vhImnLp.png "Chrome/Linux and Chrome OS/0.17.0")

On Firefox 45 on Linux (Arch kernel 4.4.6) with Nvidia proprietary drivers, the map looks good, but none of the labels show up:

![Firefox](http://i.imgur.com/g8tNSGR.png "Firefox/Linux")

On Windows 10, Firefox and Chrome show the map as expected, as does Chrome on Android, as does Chrome and Firefox on a *different* Arch box with intel graphics. 0.16.0 shows the map as expected everywhere. No console errors show up on any browser/platform, and I'm not seeing any network requests that are failing. If I swap 0.17.0 for 0.16.0 in the jsbin everything looks right again on every platform.

So...weird. If it were just one of my Arch boxes I'd dismiss it as a personal problem, but it's happening on Chrome OS devices as well, and it's specific to 0.17.0. I logged in as a guest on Chrome OS it to make sure a wayward browser extension wasn't raining on my parade.

I imagine this may be too difficult to simulate to fix, I just wanted to report it in case others are running into the same problem.

**Comment by skokenes** [comment]
Yea I am having issues as well with 0.17.0. I cannot add a geojson layer of circles to a map. I am running on a MacBook Pro with NVIDIA GeForce GT 650M, assuming NVIDIA drivers...

In Chrome 49, works fine:
![screen shot 2016-04-20 at 2 39 51 pm](https://cloud.githubusercontent.com/assets/5554373/14686237/d67da8aa-0705-11e6-86d6-7a6cef192ee0.png)

In Firefox 45, I get no circles and some errors in the console:
<img width="936" alt="screen shot 2016-04-20 at 2 40 07 pm" src="https://cloud.githubusercontent.com/assets/5554373/14686249/e1d4fb72-0705-11e6-8b3b-c83fc61cc67a.png">

The errors point to:
`this.modelType=modelType||jsts.geom.PrecisionModel.FLOATING;if(this.modelType===jsts.geom.PrecisionModel.FIXED){this.scale=1.0;}};jsts.geom.PrecisionModel.FLOATING='FLOATING';jsts.geom.PrecisionModel.FIXED='FIXED';jsts.geom.PrecisionModel.FLOATING_SINGLE='FLOATING_SINGLE';jsts.geom.PrecisionModel.prototype.scale=null;jsts.geom.PrecisionModel.prototype.modelType=null;jsts.geom.PrecisionModel.prototype.isFloating=function(){return this.modelType===jsts.geom.PrecisionModel.FLOATING||this.modelType===jsts.geom.PrecisionModel.FLOATING_SINLGE;};jsts.geom.PrecisionModel.prototype.getScale=function(){return this.scale;};jsts.geom.PrecisionModel.prototype.getType=function(){return this.modelType;};jsts.geom.PrecisionModel.prototype.equals=function(other){return true;if(!(other instanceof jsts.geom.PrecisionModel)){return false;}`

**Comment by nicoabie** [comment]
I'm having a similar issue upgrading from 0.16.0 to 0.17.0

We are using the map with cordova and xwalk, for some deviced we need to specify the --ignore-gpu-blacklist flag, see https://crosswalk-project.org/documentation/about/faq.html#Canvas-and-WebGL-support 

We found that on android webgl is banned in devices that:
https://code.google.com/p/chromium/codesearch#chromium/src/gpu/config/software_rendering_list_json.cc&l=749

I believe it was working on 0.16.0 because of this regression [#2408](https://github.com/mapbox/mapbox-gl-js/pull/2408)

Maybe it thinks that many workers will be able to perform their tasks but just one gets to accomplish them.

**Comment by lyxell** [comment]
I get the same behaviour as OP with v0.18.0 and Ubuntu 14.04.4 LTS x86_64.

**Comment by capaj** [comment]
I am on Ubuntu 16.04 with Nvidia drivers and I get the same issue. Left is chrome 50, right is Firefox: 
![screenshot from 2016-05-08 15-40-43](https://cloud.githubusercontent.com/assets/1305378/15098642/ed1ec0cc-1541-11e6-9985-8b24f791c00d.jpg)

**Comment by tobinbradley** [comment]
I think I've narrowed it down to a change in js/render/painter/use_program.js that occurred at HEAD=48332cb (`git checkout master~94`, and yes, I suck at git). Replacing that file with the file from `git checkout master~95` (a926371) fixes it for ~94, but that won't work with current builds (get a `util.objectValues is not a function` error).

I'll dig into it more tomorrow and see if I can figure out where the problem is between the two old versions of that file, then try to apply that to the current version.

**Comment by tobinbradley** [comment]
Found the problem. For some architectures/browsers the attributes variable in `js/render/painter/use_program.js` ~ line 94 is getting values assigned to the wrong keys. Browsers having the problem end up with something like this:

``` javascript
Object {a_pos: 0}
Object {a_pos: 0}
Object {a_data: 0, a_pos: 1}
Object {a_pos: 0}
Object {a_pos: 0}
Object {a_data: 0, a_pos: 1}
Object {a_data: 0, a_extrude: 1, a_pos: 2}
Object {a_offset: 0, a_data1: 1, a_data2: 2, a_pos: 3}
Object {a_offset: 0, a_data1: 1, a_data2: 2, a_pos: 3}
```

The nubers are right, but they're assigned to the wrong keys. The correct answer key/value pairs are:

``` javascript
Object {a_pos: 0}
Object {a_pos: 0}
Object {a_data: 1, a_pos: 0}
Object {a_pos: 0}
Object {a_data: 1, a_pos: 0}
Object {a_data: 2, a_extrude: 1, a_pos: 0}
Object {a_offset: 1, a_data1: 2, a_data2: 3, a_pos: 0}
Object {a_offset: 1, a_data1: 2, a_data2: 3, a_pos: 0}
Object {a_pos: 0}
```

If I do a little if/then fixing before the attributes data is set like so:

``` javascript
if (attributes.a_pos === 1) {
        attributes.a_data = 1;
        attributes.a_pos = 0;
    }
    if (attributes.a_pos === 2) {
        attributes.a_pos = 0;
        attributes.a_data = 2;
    }
    if (attributes.a_pos === 3) {
        attributes.a_pos = 0;
        attributes.a_offset = 1;
        attributes.a_data1 = 2;
        attributes.a_data2 = 3;
    }
```

That solves the problem. But of course, that's a terrible fix. Gotta figure out why `gl.getActiveAttrib(program, i);` fetches things in a different order on some systems.

**Comment by tobinbradley** [comment]
Ah, got it. `js\render\painter\user_program.js` line 95 needs to be changed from `attributes[attribute.name] = i;` to `attributes[attribute.name] = gl.getAttribLocation(program, attribute.name);`. I'll submit a pull request.

**Comment by lucaswoj** [comment]
Thank you @tobinbradley 👏! I'm looking forward to merging your PR. Let me know if you need anything to get that ready.
