### ISSUE TITLE
gl.update is not a function : 0.12.1

### ISSUE THREAD

**Issue by ryanbaumann** [mapbox/mapbox-gl-js#1833]
When loading a heat layer into a gl map using leaflet-mapbox-gl, I'm getting error "gl.update is not a function" from the "_update" method below when panning or zooming the map.  

This works fine in 0.12.0 -- bug was introduced in 12.1 - perhaps from the following change noted in the changelog:

Breaking changes
Made Map#update and Map#render private methods (#1798)

Function which throws error when panning/zooming map:

    _update: function () {
        var size = this._map.getSize(),
            container = this._glContainer,
            gl = this._glMap,
            topLeft = this._map.containerPointToLayerPoint([0, 0]);

        L.DomUtil.setPosition(container, topLeft);
        
        var center = this._map.getCenter();

        // gl.setView([center.lat, center.lng], this._map.getZoom() - 1, 0);
        // calling setView directly causes sync issues because it uses requestAnimFrame

        var tr = gl.transform;
        tr.center = mapboxgl.LngLat.convert([center.lng, center.lat]);
        tr.zoom = this._map.getZoom() - 1;

        if (gl.transform.width !== size.x || gl.transform.height !== size.y) {
            container.style.width  = size.x + 'px';
            container.style.height = size.y + 'px';
            gl.resize();
        } else {
            gl.update();
        }
    },

**Comment by ryanbaumann** [comment]
This is a leaflet-mapbox-gl.js library issue -- moving ticket to the appropriate repo.  Closing.
