### ISSUE TITLE
Regression: 0.45.0 breaks with "." in source ID

### ISSUE THREAD

**Issue by mike-marcacci** [mapbox/mapbox-gl-js#6660]
Beginning with 0.45.0, having a "." in a layer's ID crashes the web workers. I originally thought this was the same as #6648, but it isn't:

From [this comment](https://github.com/mapbox/mapbox-gl-js/issues/6648#issuecomment-388119635):
> I'm experiencing this too. On upgrading to `0.45.0` from `0.45.2` I get several errors in the console in Chrome (I suspect one for each worker):
> 
> ```
> this.parent.getWorkerSource(...)[a[2]] is not a function
>     at Ma.receive (blob:http://localhost:3000/c3408085-1173-4234-bfef-47ecdda464e3:1)
> ```
> 
> ![image](https://user-images.githubusercontent.com/690517/39882643-95520f34-5441-11e8-9854-0541dfb469c3.png)
> 
> Mapbox is imported with `import mapboxgl from "mapbox-gl";` and pulls in the minified `/dist/mapbox-gl.js`. I've also tried importing `mapbox-gl/dist/mapbox-gl-dev.js`, which has the same effect. The problem line appears to be [this line](https://github.com/mapbox/mapbox-gl-js/blob/master/src/util/actor.js#L92).

From [this comment](https://github.com/mapbox/mapbox-gl-js/issues/6648#issuecomment-388122207):
> Ah, ok, so the problem is the `const keys = data.type.split('.');` As of `0.45.0` it has become illegal to use a period character in your source/layer names. This is definitely a bug, as this is a pattern we use pretty extensively.
> 
> Mapbox should probably escape periods (and any other special characters) before serializing, and then unescape them when deserializing.
> 
> EDIT: looking at the `git blame`, it appears that this has been in place for a while... perhaps something else has caused it to become problematic just now?
> 
> EDIT2: Ok, so it looks like the bug was likely introduced in 373f5c4bef3fd118d6390ab01a3eb7d208793940

**mapbox-gl-js version**: 0.45.0

**browser**: Chrome 66.0.3359.170

### Steps to Trigger Behavior

 1. upgrade to 0.45.0
 2. add layers with a period in the name (ex: "mygroup.mylayer")
 3. run it

### Expected Behavior

[Expected (v0.44.0)](https://jsfiddle.net/x6v36nkc/1/)

### Actual Behavior

[Actual (v0.45.0)](https://jsfiddle.net/6h4uvvae/1/)

```
Uncaught TypeError: this.parent.getWorkerSource(...)[a[2]] is not a function
```

EDIT: I had switched the "Actual" and "Expected" links above. 🤦🏻‍♂️

**Comment by anandthakker** [comment]
Ah, thanks @mike-marcacci!  And yes, I think you're right that https://github.com/mapbox/mapbox-gl-js/commit/373f5c4bef3fd118d6390ab01a3eb7d208793940#diff-cab2e47d8b0edbe014f919bc172194b2 introduced the problem: before that, the `data.type` property was comprised of source type and method name, neither of which would have included a `.`

**Comment by anandthakker** [comment]
Note: retitled the issue to refer to _source_ ID, rather than layer ID.  They happen to be the same when source data is provided as part of the layer definition, as in the OP's examples, but the underlying issue is about the source ID.

**Comment by ChrisLoer** [comment]
Fixed on `master` with #6700.
