### ISSUE TITLE
workerClass seems s broken with angular 17's new application builder

### ISSUE THREAD

**Issue by BouckaertThibault** [mapbox/mapbox-gl-js#13131]
**mapbox-gl-js version**: 3.2.0

**browser**: Latest chrome

### Steps to Trigger Behavior
Not sure if this is a mapbox or a angular issue.

In the browser builder with webpack I was able to use
workerClass: require("worker-loader!../../node_modules/mapbox-gl/dist/mapbox-gl-csp-worker").default,
to import a worker. Using the new application builder I was using vite's way to import a worker which was through
import MapboxGLWorker from "mapbox-gl/dist/mapbox-gl-csp-worker?worker"; workerClass: MapboxGLWorker

This works but only when using the development server (ng serve). Building the application with ng build or when serving with the --prebundle=false argument results in a main.ts:5 ERROR TypeError: ug.workerClass is not a constructor error in the browser

I then came accross https://github.com/angular/angular-cli/issues/27323 which was similar so I tried the new Worker() method which still results in the same error.

### Link to Demonstration

1. Clone https://github.com/BouckaertThibault/angular-17-mapbox-csp (a dummy access token is already provided)
2. npm install
3. ng serve --prebundle=false

### Expected Behavior

mapbox loads normally

### Actual Behavior

ERROR TypeError: ug.workerClass is not a constructor
    at new hg (mapbox-gl-csp.js:3:304799)
    at WorkerPool.acquire (mapbox-gl-csp.js:3:305062)
    at new Dispatcher (mapbox-gl-csp.js:3:284920)
    at new Style (mapbox-gl-csp.js:3:693886)
    at Map._updateStyle (mapbox-gl-csp.js:3:828788)
    at Map.setStyle (mapbox-gl-csp.js:3:828538)
    at new Map (mapbox-gl-csp.js:3:818918)
    at _AppComponent.<anonymous> (app.component.ts:22:16)
    at Generator.next (<anonymous>)
    at main.js:72:61

**Comment by stepankuzmin** [comment]
Hi @BouckaertThibault,

Does the same setup work with Mapbox GL JS `v3.2.0-beta.1` or `v3.1.2`? Also, does `ng build` or serving with the `--prebundle=false` transpiles the `mapbox-gl-csp-worker` code you import? Do you use `webpack-worker-loader`?

**Comment by BouckaertThibault** [comment]
Using another version of mapbox did not solve the issue. webpack-worker-loader is not used as the new builder of angular uses vite, not webpack.

I was able to fix the issue by wrapping the worker in a function like below:

```
import mapboxgl from "mapbox-gl/dist/mapbox-gl-csp";

...

mapboxgl.workerClass = function () {
  return new Worker(new URL("./mapbox.worker", import.meta.url));
};

```
