### ISSUE TITLE
'map.on is not a function' error after: 'MapboxGL fails outside browser (e.g. with jsdom) throwing 'createObjectURL is not a function' '

### ISSUE THREAD

**Issue by brdv** [mapbox/mapbox-gl-js#10236]
**mapbox-gl-js 2.0.0:**

## **Project Setup**

Using mapbox 2.0.0 in a create-react-app with react v17.0.1 and typescript 4.0.3.

## **Steps to Trigger Behavior**

Create map component according to [docs](https://docs.mapbox.com/help/tutorials/use-mapbox-gl-js-with-react/) and setup basic test. Run `yarn test` will firstly trigger error 1 below. After applying [this](https://github.com/mapbox/mapbox-gl-js/issues/3436#issuecomment-485535598) fix, error 2 below occurs.

## **Expected Behavior**

No error

## **Actual Behavior**

Error 1:
`TypeError: window.URL.createObjectURL is not a function
`
Error 2:
`TypeError: map.on is not a function`

## **Consequences**

It is not possible to use Mapbox and run tests successfully this way, as the tests will fail.

## **Question**

Is there anybody who can help me get the tests running? Or tell me what I might be doing wrong?

Thanks in advance!

**Comment by brdv** [comment]
After updating to V2.0.1 this problem no longer persists.

**Comment by kahummer** [comment]
@brdv I'm still experiencing the same error after upgrading to V2.0.1 is there another workaround?

**Comment by brdv** [comment]
@kahummer We're still experiencing the error as wel now, opened a new (more elaborate) issue: https://github.com/mapbox/mapbox-gl-js/issues/10583

**Comment by lstuma** [comment]
`map.current.on` raises error cuz it is `undefinded`

**Comment by kreshnik01** [comment]
> `map.current.on` raises error cuz it is `undefinded`

How you're defining map instance?
