### ISSUE TITLE
Property 'setprojection' does not exist on type 'Map'

### ISSUE THREAD

**Issue by spiderdab** [mapbox/mapbox-gl-js#12283]
mapbox-gl-js version: 2.10.0
I'm working with Angular 14.2.1
also added: npm install --save @types/mapbox-gl

### Question
Made a new Angular project, installed mapbox-gl as per instruction here: https://docs.mapbox.com/mapbox-gl-js/guides/install/

I've setup a simple 'globe' map using the property:
this.map = new Mapboxgl.Map({
....
      projection: {
        name: 'globe'
      }
    });

and the property projection works as expected, but if I want to change the projection type using map.setProjection('mercator'), as documented here: https://docs.mapbox.com/mapbox-gl-js/guides/projections/
the function is not recognized, giving me this error: 
error TS2339: Property 'setprojection' does not exist on type 'Map'.

What am I doing wrong?

**Comment by Sh1-5** [comment]
setProjection does not defined in @types/mapbox-gl
(map as any).setProjection

**Comment by Sh1-5** [comment]
can you commit a pr
https://github.com/DefinitelyTyped/DefinitelyTyped

**Comment by spiderdab** [comment]
I don't know how to fix this. I'm new to Types.

**Comment by mourner** [comment]
Yeah, this is an issue with outdated community-contributed [type definitions of mapbox-gl](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/mapbox-gl) on DefinitelyTyped. It's maintained by the community, not our team, and circumventing the type error is more of a generic typing question than GL JS specific, so I'll have to close the issue.

**Comment by cooljeffro** [comment]
@types/mapbox-gl 2.7.10 added setProjection()
