### ISSUE TITLE
Bug in `query-similar-features` Example on Mapbox Site

### ISSUE THREAD

**Issue by KaiBot3000** [mapbox/mapbox-gl-js#3025]
**mapbox-gl.js v0.22.0**:

### Steps to Trigger Behavior

 1. Visit https://www.mapbox.com/mapbox-gl-js/example/query-similar-features/
 2. Open developer console
 3. Hover over counties on map

### Expected Behavior
Something on the map to change in response to user interaction

### Actual Behavior
`query_features.js:26 Uncaught TypeError: e.renderedIDs is not a function`, and nothing changes on the map

#### Note
I checked this out in Chrome and Safari and saw the same behavior. I'm not sure what's actually supposed to happen so this will be fun 😸

**Comment by peterqliu** [comment]
Looks like a regression with v.0.22.0; this worked in 0.21.0 ([jsfiddle](https://jsfiddle.net/8qrfo41n/)).

My stack trace is pointing to the `querySourceFeatures` line.

**Comment by peterqliu** [comment]
likely related: https://github.com/mapbox/mapbox-gl-js/pull/3022

**Comment by lucaswoj** [comment]
This was fixed in #3022
