### ISSUE TITLE
dependency list

### ISSUE THREAD

**Issue by pnorman** [mapbox/mapbox-gl-js#828]
The documentation does not contain a dependency list. It would be useful.

I had to install the glew headers (`libglew-dev` on debian-based systems), but I don't know what other requirements there are, other than a C compiler.

**Comment by tristen** [comment]
@pnorman is still an issue? `npm install` should cover all deps from the looks of it.

**Comment by jfirebaugh** [comment]
There are no additional dependencies for production use. However, to run the headless rendering tests, libglew-dev and imagemagick are required.

**Comment by pnorman** [comment]
> @pnorman is this still an issue? npm install should cover all deps from the looks of it.

I tested and `npm install && npm start` now works on Ubuntu 14.04 with only git, npm and nodejs-legacy installed.

> However, to run the headless rendering tests, libglew-dev and imagemagick are required.

On the same VM I tried `npm test` with git, npm, nodejs-legacy, libglew-dev, imagemagick, and pastebinit (to get the text out of the vm) installed.

I got the error
```

> mapbox-gl@0.7.0 test /home/pnorman/mapbox-gl-js
> npm run lint && tape test/js/*/*.js


> mapbox-gl@0.7.0 lint /home/pnorman/mapbox-gl-js
> eslint js test


module.js:340
    throw err;
          ^
Error: Cannot find module 'gl'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/pnorman/mapbox-gl-js/js/util/canvas.js:6:10)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
npm ERR! weird error 8
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm ERR! not ok code 0
```

**Comment by jfirebaugh** [comment]
@pnorman You'll need to rerun `npm install` after installing libglew-dev.

**Comment by pnorman** [comment]
> @pnorman You'll need to rerun npm install after installing libglew-dev.

Still failing.

Full script, starting from a clone of the clean 14.04 virtualbox VM I keep

```
sudo apt-get update
sudo apt-get upgrade -y
sudo apt-get --no-install-recommends -y install git npm nodejs-legacy libglew-dev imagemagik pastebinit # wait...
git clone http://github.com/mapbox/mapbox-gl-js.git
cd mapbox-gl-js
npm install # wait...
npm test
```

This produces the error above.

**Comment by jfirebaugh** [comment]
@pnorman Can you gist the output?

**Comment by pnorman** [comment]
Which output? The output of `npm test` is [above](https://github.com/mapbox/mapbox-gl-js/issues/828#issuecomment-77459404)

**Comment by jfirebaugh** [comment]
Of the entire sequence of commands.

**Comment by pnorman** [comment]
https://gist.github.com/pnorman/debf8327f8e753f916de has logs, except for the initial update and upgrade

**Comment by jfirebaugh** [comment]
From `npm_install.log`:

```
gyp ERR! stack Error: not found: make
```

Is `make` really not installed?

**Comment by pnorman** [comment]
`make` is not a dependency of libglew-dev, imagemagick, or npm - nor is it part of a stock Ubuntu install. 

There's a few other optional dependencies which have failed too.

**Comment by Jinnified** [comment]
so, did you find a solution for this?
